### ISSUE TITLE
Consider adding an option to append or prepend changelogs

### ISSUE THREAD

**Issue by marcospassos** [switchtrue/JIRAChangelogBuilder#21]
We have a use case that every time we release a new version, the changelog is generated and appended to the the current one. Currently, we achieve that generating a new file and using command to merge them.

If you consider useful, I can work on that and open a pull request.

**Comment by switchtrue** [comment]
Currently it re-generates the change log each time it is run and it get the order based on the "Release Date" of a version in JIRA. The versions are then written out in reverse date order.

I would suggest adding a new optional command line flag of "--output-order" which can take a mandatory option "DATE_DESC" or "DATE_ASC" to do the appropriate sorting. This should default to "DATE_DESC" for backward compatibility.

For you to achieve append functionality you would simply specify "--output-order DATE_ASC".

I would be happy for you to work on this and submit a pull request. The following code will be relevant:
- The sorting is executed at line 198 of net.foxopen.jira.changelog.JiraAPI
- The sorting is implemented using a DateComparator class defined in JiraAPI at line 236.

I suggest you modify the DateComparator class be be able to be toggled between ascending and descending method so that the compare function return appropriately.

**Comment by marcospassos** [comment]
@mleonard87 something is not clear for me: does the builder generate the entire changelog every time that it run? (it makes sense looking in the mustache template). If so, what is the purpose of the `version` parameter?

**Comment by switchtrue** [comment]
Yes, it rebuilds it every time (however, if you've specified `--object-cache-path` the vast majority will be cached for performance reasons).

The purpose of the `version` parameter is basically to tell the builder when to stop adding versions to the changelog. For example you might have many versions already added to JIRA as part of future planning and we may not want to include these future releases in the change log.

The changelog builder gets the release date of the version specified by `version` and find all other version released before it.

In practice this will usually equate to "get me everything thats been released on or before today" but it allows us a little more flexibility. For example you could generate a changelog for a future build in order to give an early preview to the issues being fixed in the next release.

**Comment by marcospassos** [comment]
Ok, it's clear now. In that way, it solves my problem. But, again, it's not clear in the documentation. In the way I understood, the `version` parameter tells the builder to generate the changelog for a specific version, but in fact it limits the generation _up to_ a specific version. Can I change this information to make it more explicit?

**Comment by switchtrue** [comment]
Absolutely, send through a pull request.

**Comment by switchtrue** [comment]
This issue will be further resolved with issue #27.
